name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/mortinelli/devops90days:test .

      - name: Push Docker image
        run: |
          docker push ghcr.io/mortinelli/devops90days:test
      - name: Deploy to VM
        run: |
          # --- prepare SSH key ---
          mkdir -p ~/.ssh
          printf '%s\n' "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          # --- deploy over SSH ---

          ssh -i ~/.ssh/id_ed25519 \
              -o StrictHostKeyChecking=no \
              devopsadmin@${{ secrets.VM_HOST }} \
              "docker pull ghcr.io/mortinelli/devops90days:test &&
              docker ps -aq --filter 'name=devops90days' | xargs -r docker stop &&
              docker ps -aq --filter 'name=devops90days' | xargs -r docker rm &&
              docker run -d --name devops90days -p 8080:80 ghcr.io/mortinelli/devops90days:test"

           rm -f ~/.ssh/id_ed25519

